import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Carousel from "../components/carousel/Carousel";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import Call from "../components/personalInfo/PersonalInfo";
import PersonalInfo from "../components/personalInfo/PersonalInfo";
import CallAction from "../components/callAction/CallAction";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div>
          <PersonalInfo />
        </div>
        <div className="container">
          <Carousel />
        </div>
        <div className="container">
          <CallAction />
        </div>

        <Footer />
      </main>
    </>
  );
}

